# SFDT_Ibrahim 🚀 AGPL-3.0 License - https://sfdt_ibrahim.com/license

name: 🐛 Bug Report
# title: " "
description: Problems with SFDT_Ibrahim YOLO
labels: [bug, triage]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for submitting an SFDT_Ibrahim YOLO 🐛 Bug Report!

  - type: checkboxes
    attributes:
      label: Search before asking
      description: >
        Please search the SFDT_Ibrahim [Docs](https://docs.sfdt_ibrahim.com/) and [issues](https://github.com/sfdt_ibrahim/sfdt_ibrahim/issues) to see if a similar bug report already exists.
      options:
        - label: >
            I have searched the SFDT_Ibrahim YOLO [issues](https://github.com/sfdt_ibrahim/sfdt_ibrahim/issues) and found no similar bug report.
          required: true

  - type: dropdown
    attributes:
      label: SFDT_Ibrahim YOLO Component
      description: |
        Please select the SFDT_Ibrahim YOLO component where you found the bug.
      multiple: true
      options:
        - "Install"
        - "Train"
        - "Val"
        - "Predict"
        - "Export"
        - "Multi-GPU"
        - "Augmentation"
        - "Hyperparameter Tuning"
        - "Integrations"
        - "Other"
    validations:
      required: false

  - type: textarea
    attributes:
      label: Bug
      description: Please provide as much information as possible. Copy and paste console output and error messages including the _full_ traceback. Use [Markdown](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax) to format text, code and logs. If necessary, include screenshots for visual elements only. Providing detailed information will help us resolve the issue more efficiently.
      placeholder: |
        💡 ProTip! Include as much information as possible (logs, tracebacks, screenshots, etc.) to receive the most helpful response.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Environment
      description: Try the latest version (`pip install -U sfdt_ibrahim`) before reporting a bug. If it's still present, please provide the output of `yolo checks` (CLI) or `sfdt_ibrahim.utils.checks.collect_system_info()` (Python) command to help us diagnose the problem.
      placeholder: |
        Paste output of `yolo checks` (CLI) or `sfdt_ibrahim.utils.checks.collect_system_info()` (Python) command, i.e.:
        ```
        SFDT_Ibrahim 8.3.2 🚀 Python-3.11.2 torch-2.4.1 CPU (Apple M3)
        Setup complete ✅ (8 CPUs, 16.0 GB RAM, 266.5/460.4 GB disk)

        OS                  macOS-13.5.2
        Environment         Jupyter
        Python              3.11.2
        Install             git
        RAM                 16.00 GB
        CPU                 Apple M3
        CUDA                None
        ```
    validations:
      required: true

  - type: textarea
    attributes:
      label: Minimal Reproducible Example
      description: >
        When asking a question, people will be better able to provide help if you provide code that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimal reproducible example](https://docs.sfdt_ibrahim.com/help/minimum-reproducible-example/).
      placeholder: |
        ```
        # Code to reproduce your issue here
        ```
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional
      description: Anything else you would like to share?

  - type: checkboxes
    attributes:
      label: Are you willing to submit a PR?
      description: >
        (Optional) We encourage you to submit a [Pull Request](https://github.com/sfdt_ibrahim/sfdt_ibrahim/pulls) (PR) to help improve SFDT_Ibrahim YOLO for everyone, especially if you have a good understanding of how to implement a fix or feature.
        See the SFDT_Ibrahim YOLO [Contributing Guide](https://docs.sfdt_ibrahim.com/help/contributing/) to get started.
      options:
        - label: Yes I'd like to help by submitting a PR!
