# SFDT_Ibrahim 🚀 AGPL-3.0 License - https://sfdt_ibrahim.com/license

name: 🚀 Feature Request
description: Suggest an SFDT_Ibrahim YOLO idea
# title: " "
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for submitting an SFDT_Ibrahim 🚀 Feature Request!

  - type: checkboxes
    attributes:
      label: Search before asking
      description: >
        Please search the SFDT_Ibrahim [Docs](https://docs.sfdt_ibrahim.com/) and [issues](https://github.com/sfdt_ibrahim/sfdt_ibrahim/issues) to see if a similar feature request already exists.
      options:
        - label: >
            I have searched the SFDT_Ibrahim [issues](https://github.com/sfdt_ibrahim/sfdt_ibrahim/issues) and found no similar feature requests.
          required: true

  - type: textarea
    attributes:
      label: Description
      description: A short description of your feature.
      placeholder: |
        What new feature would you like to see in YOLO?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Use case
      description: |
        Describe the use case of your feature request. It will help us understand and prioritize the feature request.
      placeholder: |
        How would this feature be used, and who would use it?

  - type: textarea
    attributes:
      label: Additional
      description: Anything else you would like to share?

  - type: checkboxes
    attributes:
      label: Are you willing to submit a PR?
      description: >
        (Optional) We encourage you to submit a [Pull Request](https://github.com/sfdt_ibrahim/sfdt_ibrahim/pulls) (PR) to help improve YOLO for everyone, especially if you have a good understanding of how to implement a fix or feature.
        See the SFDT_Ibrahim [Contributing Guide](https://docs.sfdt_ibrahim.com/help/contributing/) to get started.
      options:
        - label: Yes I'd like to help by submitting a PR!
